$kind: http-example
request:
  url: "{{bhom_base_url}}/metrics-query-service/api/v1.0/label/instanceName/values"
  method: GET
  headers:
    - key: Content-Type
      value: application/json
    - key: Authorization
      value: apiKey {{bhom_apiKey}}
    - key: ""
      value: ""
      disabled: true
response:
  statusCode: 200
  statusText: OK
  headers:
    Date: Tue, 11 Jul 2023 17:05:22 GMT
    Content-Type: application/json
    Transfer-Encoding: chunked
    Connection: keep-alive
    Access-Control-Allow-Origin: "*"
    Permissions-Policy: idle-detection=self
    Pragma: no-cache
    Referrer-Policy: same-origin
    X-Server-Hostname: victoria-metrics-victoria-metrics-cluster-vmselect-5c89554skbt2
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    Content-Encoding: gzip
    TraceId: 38360cc0-d204-4cbe-b07d-a4ef585940f7 null
    Vary: Accept-Encoding
    Cache-control: no-store
  body:
    type: json
    content: |-
      {
          "status": "success",
          "isPartial": false,
          "data": [
              "pat_sim1.bmc.com:3181",
              "pat_sim2.bmc.com:3181",
              "pat_sim3.bmc.com:3181",
              "pat_sim4.bmc.com:3181",
              "pat_sim5.bmc.com:3181"
          ]
      }
order: 6000
